import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Banner from "./components/Banner";
import ClassForm from "./components/ClassForm";
import Footer from "./components/Footer";
import NavBar from "./components/NavBar";
import {auth} from '../firebase';
import { useAuthState } from "react-firebase-hooks/auth";
import { useEffect,useState } from "react";

export default function Home() {
  const  [user, setUser] = useAuthState(auth);
  const [myPass, setMyPass] = useState();
  const [passDetails, setPassDetails] = useState([]);
  

  return (
    <div className={styles.container}>
    
      <Head>
        <title>Yoga Classes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=" ">
        <NavBar user={user} />
        <Banner />
        <div className="m-4 flex flex-col md:flex-row justify-between space-x-10">

          <ClassForm user={user} />
          <div className="md:m-0 m-4 ">
            <h1 className="  text-3xl text-semibold" >Yoga Classes</h1>
            <p className="text-gray-400 my-3 text-sm font-semibold">Yoga is an Art and Science of healthy living. It is a spiritual discipline  based on an extremely subtle science, which focuses on bringing harmony between mind and body. The holistic approach of Yoga is well established and it brings harmony in all walks of life and thus, known for disease prevention, promotion of health and management of many lifestyle –related disorders. Today, Yoga is popular across the globe, not just because of its efficacy in the management of some diseases, but also of its strength in providing relief to the practitioner, from mental and emotional distress and  providing a feeling of well-being. Hence, now-a-days Yoga is being practiced as part of healthy life style across the globe.<br/><br/>
            The term Yoga is derived from the Sanskrit root ‘YUJ’, meaning ‘to join’ or ‘to yoke’ or ‘to unite’. As per Yogic scriptures the practice of Yoga leads to the union of individual consciousness with that of the Universal Consciousness, indicating a perfect harmony between the mind and body, Man & Nature. The aim of Yoga is Self-Realization, to overcome all kinds of sufferings leading to 'the state of liberation'. This is one of the oldest sciences of the world, which originated in India. Yoga is very useful for preserving and maintaining one's physical and mental health and also for  'spiritual evolution'. The practice of Yoga is believed to have started with the very dawn of civilization.</p>
          </div>
          <div className="relative top-0 h-42  w-full">

          <Image draggable="false" src="/sideBanner.png" fill className=" w-full rounded-md object-cover" />
          </div>
        </div>
      </main>

      <Footer />
    </div>
  );
}
